# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jmapping - In The Wild
email: j.mapping@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "jmapping" # the subpath of your site, e.g. /blog
lang: "en"
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: jmapping
github_username:  justinlewis
disqus_username:

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass
  style: compressed


images: '/assets/images'

projects:
- name: GeoPrism
  url: https://github.com/terraframe/geoprism
  code-url: https://github.com/terraframe/geoprism
  description: is a powerful enterprise level open source visualization layer that runs on the powerful data engine RunwaySDK.  It offers a huge variety of features for users that need the ability to work with data, data visualization, and reporting through simple web-widgets.  This project is being developed by my day-job team at TerraFrame.

- name: RunwaySDK
  url: https://github.com/terraframe/Runway-SDK
  code-url: https://github.com/terraframe/Runway-SDK
  description: is a powerful enterprise level open source visualization layer that runs on the powerful data engine RunwaySDK.  It offers a huge variety of features for users that need the ability to work with data, data visualization, and reporting through simple web-widgets.  This project is being developed by my day-job team at TerraFrame.

- name: ClimbMapper
  url: http://www.climbmapper.com/
  code-url: https://github.com/justinlewis/climbmapper
  description: is an experimental application that was inspired by the desire to visualize climbing areas in terms of what locations a climber should visit based on the climbs they want to do there.  It is constantly evolving as the process of planning for climbing is explored through modern technology. Built on Node.js, PostGIS, D3.js, Leaflet.js, and JQuery.js.

- name: 2013 Colorado Flood Visualization
  url: http://justinlewis.github.io/colorado_flood_vis_2013/
  code-url: https://github.com/justinlewis/colorado_flood_vis_2013
  description: is a powerful enterprise level open source visualization layer that runs on the powerful data engine RunwaySDK.  It offers a huge variety of features for users that need the ability to work with data, data visualization, and reporting through simple web-widgets.  This project is being developed by my day-job team at TerraFrame.
