# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: About JMapping
email: j.mapping@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
lang: "en"
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: jmapping
github_username:  justinlewis
disqus_username:

# Build settings
markdown: kramdown
permalink: /:categories/:title/

exclude: [writings.md]

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass
  style: compressed


images: '/assets/images'

projects:
- name: GeoPrism
  url: https://github.com/terraframe/geoprism
  code-url: https://github.com/terraframe/geoprism
  description: is a powerful enterprise level open source visualization layer that runs on the powerful data engine RunwaySDK.  It offers a huge variety of features for users that need the ability to work with data, data visualization, and reporting through simple web-widgets.  This project is being developed by my day-job team at TerraFrame.

- name: RunwaySDK
  url: https://github.com/terraframe/Runway-SDK
  code-url: https://github.com/terraframe/Runway-SDK
  description: is a powerful enterprise level open source data engine with a particular niche in structuring data as Ontologies.  It is a very robust framework for building applications where data integrity is the top priority.  This project is being developed by my day-job team at TerraFrame.

- name: Digital Solutions For Malaria Elimination Partner
  url: https://dsme.community/
  code-url: https://github.com/terraframe/geoprism-registry
  description: is a collaborative effort to build a suite of technology to help mitigate Malaria in key countries. I (and the TerraFrame team) are helping define global standards for data transmission as well as building the Common Geospatial Registry.

- name: Roaring Fork Technologists
  url: http://roaringforktechnologists.com/
  code-url: https://github.com/RoaringForkTech
  description: Founded a technology group focused on supporting the technology and entrepeneurial communities round the Roaring Fork of Colorado. We write code, educate the youth, educate each other, and support local business throug volunteer technology advice.

- name: Built From Here
  url: https://builtfromhere.com/
  code-url:
  description: Stories about how and why people are building tech teams in the less populated parts of the world.
